version: "3.8"
services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      TELOXIDE_TOKEN: ${TELEGRAM_TOKEN}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      RUST_LOG: info
  mongodb:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

